data: 'kinetics_skeleton'
data_param:
  train_data_param:
    data_path: /your/path/to/Kinetics/DSTA/train_data_joint.npy
    label_path: /your/path/to/Kinetics/DSTA/train_label.pkl
    random_choose: True
    center_choose: False
    window_size: 150
    final_size: 128
    num_skip_frame:
    decouple_spatial: False
  val_data_param:
    data_path: /your/path/to/Kinetics/DSTA/val_data_joint.npy
    label_path: /your/path/to/Kinetics/DSTA/val_label.pkl
    random_choose: False
    center_choose: True
    window_size: 150
    final_size: 128
    num_skip_frame:
    decouple_spatial: False

# model
model: 'st2ransformer_dsta'
class_num: 400
model_param:
  num_point: 18
  num_frame: 128
  num_subset: 8
  num_person: 1
  num_channel: 2
  glo_reg_s: True
  att_s: True
  glo_reg_t: False
  att_t: False
  dropout: 0
  attentiondrop: 0
  dropout2d: 0
  use_spatial_att: True
  use_temporal_att: False
  use_pet: False
  use_pes: False
  config: [ [64, 64, 16, 1], [64, 64, 16, 1],
            [64, 128, 32, 2], [128, 128, 32, 1],
            [128, 256, 64, 2], [256, 256, 64, 1],
            [256, 256, 64, 1], [256, 256, 64, 1],
  ]


train: 'classify'
mode: 'train_val'
loss: 'cross_entropy'
batch_size: 32
worker: 32
pin_memory: False
num_epoch_per_save: 10
model_saved_name: './work_dir/kinetics/baseline'
last_model:
pre_trained_model:
ignore_weights: ['fc']
label_smoothing_num: 0
mix_up_num: 0
device_id: [0,1,2,3]
cuda_visible_device: '0,1,2,3'
debug: False

# lr
lr_scheduler: 'reduce_by_epoch'
lr_param:
  step: [80, 110]
#  lr_patience: 10
#  lr_threshold: 0.0001
#  lr_delay: 0
warm_up_epoch: 5
max_epoch: 180
lr: 0.1
wd: 0.0005
lr_decay_ratio: 0.1
lr_multi_keys: []

# optimizer
optimizer: 'sgd_nev'
freeze_keys: []

